import type { Metadata } from 'next'
import './globals.css'
import StyledComponentsRegistry from '@/lib/registry'

import { UserProvider } from '@/components/contexts/userContext';

import montserrat from './fonts/index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {' '}
        <StyledComponentsRegistry>
          <UserProvider>
            {children}
          </UserProvider>
        </StyledComponentsRegistry>{' '}
      </body>
    </html>
  )
}
